situation_report_compilation:
  description: >
    Consolidate subplans from all crews into a comprehensive situation report. If the other crews have raised ethical issues, combine them in the ethical_issues 
    field, ethical issues are the cases in which the resources are not enough to save all the people and a decision has to be made whether to save one person or 
    the other.

    The subplans are in the files:
    ["task3\city_emergency_response_flow\src\city_emergency_response_flow\crews\firefighting_crew\crew_outputs\008_final_plan_compilation.json",
    "task3\city_emergency_response_flow\src\city_emergency_response_flow\crews\medical_crew\crew_outputs\008_medical_final_plan_compilation.json",
    "task3\city_emergency_response_flow\src\city_emergency_response_flow\crews\police_crew\crew_outputs\005_police_final_plan_compilation.json"]

    read them using the FileReadTool.
  expected_output: >
    A detailed situation report covering all aspects of the emergency.
  agent: distributor

ethical_consultation:
  description: >
    Evaluate the consolidated plans for ethical concerns and provide recommendations. Ethical issues are the cases in which the resources are not enough to 
    save all the people and a decision has to be made whether to save one person or the other. If there are ethical issues use the FileReadTool to get the
    ethics book. Solve the ethics issues ONLY using the contents of the ethics book.
  expected_output: >
    A finalized situation report addressing ethical concerns.
  agent: philosopher
