ethical_consultation:
  description: >
    Find ethical issues in the following emergency plan. Use the ethics book using the FileReadTool to help you in this process:

    {emergency_plan}
  expected_output: >
    A flowing, precise text that includes all identified ethics issues and how they should be resolved. Arrange these steps in paragraphs following the given order or a clear chronological sequence, ensuring all details from the input plan data are included. If any ethical concerns are noted (e.g., resource scarcity decisions), address them within the text as well.
  agent: philosopher
