situation_report_compilation:
  description: >
    Consolidate subplans from all crews into a comprehensive situation report.
  expected_output: >
    A detailed situation report covering all aspects of the emergency.
  agent: distributor

ethical_consultation:
  description: >
    Evaluate the consolidated plans for ethical concerns and provide recommendations.
  expected_output: >
    A finalized situation report addressing ethical concerns.
  agent: philosopher
