# Police Crew Tasks
police_taskforce_assignment:
  description: >
    Assign police officers required for managing the traffic close to the emergency based on the given information ({police_information}).
  expected_output: >
    A count of required officers and an action plan for their deployment.
  agent: receiver_and_personnel_specialist

perimeter_control_planning:
  description: >
    Plan safety perimeters to secure the area around the emergency site based on the police action specific information ({police_information})..
  expected_output: >
    Proposed perimeter locations with an explanation of the strategy.
  agent: traffic_specialist

patrol_vehicle_assignment:
  description: >
    Assign patrol vehicles using the police information ({police_information}) and the available patrol vehicles provided by the FileReading tool. Evaluate proximity and suitability of each patrol for the tasks at hand. Also find out the position of those selected patrol vehicles. IMPORTANT: Selected patrols must have patrol_status: Available
  expected_output: >
    A list of assigned vehicles and an explanation of their allocation.
  agent: dispatch_specialist

patrol_route_planning:
  description: >
    Plan the most efficient routes for police vehicles using the police information ({police_information}) and the result of the police vehicle selection in the context, ensuring timely arrival at the emergency site. For this, the Emergency Route Tool should be used. The input to such tools should be a stringified list of the selected patrol Ids, their latitudes, and longitudes; along with floats for the emergency site's latitude and longitude.
  expected_output: >
    Optimized patrol routes and a routing strategy explanation.
  agent: dispatch_specialist

police_final_plan_compilation:
  description: >
    Compile all outputs into a comprehensive police response plan. This final plan must include all outputs from before tasks. The context includes all outputs of prior tasks and ({police_information}) includes the initial information which has been passed in the beginning.
  expected_output: >
    A complete police response plan addressing all aspects of the operation.
  agent: receiver_and_personnel_specialist
