# Police Crew Tasks
police_taskforce_assignment:
  description: >
    Assign police officers required for managing the emergency.
  expected_output: >
    A count of required officers and an action plan for their deployment.
  agent: receiver_and_personnel_specialist

perimeter_control_planning:
  description: >
    Plan safety perimeters to secure the area around the emergency site.
  expected_output: >
    Proposed perimeter locations with an explanation of the strategy.
  agent: traffic_specialist

patrol_vehicle_assignment:
  description: >
    Assign patrol vehicles to monitor perimeters and support evacuation.
  expected_output: >
    A list of assigned vehicles and an explanation of their allocation.
  agent: dispatch_specialist

patrol_route_planning:
  description: >
    Plan efficient patrol routes to ensure safety perimeters are monitored effectively.
  expected_output: >
    Optimized patrol routes and a routing strategy explanation.
  agent: dispatch_specialist

police_final_plan_compilation:
  description: >
    Compile all outputs into a comprehensive police response plan.
  expected_output: >
    A complete police response plan addressing all aspects of the operation.
  agent: receiver_and_personnel_specialist
