# Firefighting Crew Tasks

taskforce_assignment:
  description: >
    Analyze the provided firefighting information ({firefighting_information}) to assign the number of firefighters required for the emergency. Inputs such as fire type, location, injured people, and estimated severity will be used to determine the taskforce allocation.
  expected_output: >
    A count of firefighters needed along with a detailed action plan explaining the allocation decisions.
  agent: fire_personnel_specialist

extinguishing_tools_selection:
  description: >
    Use the firefighting information ({firefighting_information}) to select appropriate extinguishing tools based on the fire type and related variables.
  expected_output: >
    A list of firefighting tools selected along with an explanation of their relevance to the fire type and conditions.
  agent: fire_type_specialist

building_structure_assessment:
  description: >
    Evaluate the structural integrity of the building at the fire location using the firefighting information ({firefighting_information}). Develop rescue and fire suppression strategies tailored to the situation.
  expected_output: >
    A rescue strategy, fire suppression strategy, and a detailed explanation of the assessment process.
  agent: building_structure_specialist

victim_rescue_planning:
  description: >
    Analyze the firefighting information ({firefighting_information}) to prioritize the rescue of injured individuals. Consider their conditions and the severity of injuries.
  expected_output: >
    An ordered list of victims for rescue along with a detailed explanation of the prioritization logic.
  agent: rescue_specialist

tool_selection:
  description: >
    Use the firefighting information ({firefighting_information}) and strategies developed in the context to select additional firefighting tools required for rescue and fire suppression.
  expected_output: >
    A list of selected firefighting tools and an explanation of why they were chosen based on the situation.
  agent: tool_specialist

fire_truck_selection:
  description: >
    Assign fire trucks using the firefighting information ({firefighting_information}) and the context which gives information about the necessary extinguishing tools which you need to install on the trucks you select. Evaluate proximity and suitability of each truck for the tasks at hand. Also find out the position of those fire trucks.
  expected_output: >
    A list of selected fire trucks, each's equipment and their locations with a rationale for the selection process.
  agent: fire_truck_chief

route_planning:
  description: >
    Plan the most efficient routes for fire trucks using the firefighting information ({firefighting_information}) and the result of the fire truck selection in the context, ensuring timely arrival at the emergency site.
  expected_output: >
    Optimized routes along with a detailed explanation of the routing logic.
  agent: fire_truck_chief

final_plan_compilation:
  description: >
    Consolidate all outputs from previous tasks to create a comprehensive firefighting response plan using the firefighting information ({firefighting_information}) and all outputs of tasks from before given in the context. Include all strategies, tools, routes, and personnel information derived from the input.
    The ethical issues considered should ONLY regard cases where the resources are not enough for the problem, if there is a situation where you have to choose between saving one person 
    or the other, no decision should be made, instead the ethical dilemma should be stated in the ethical issues output.
  expected_output: >
    A complete firefighting response plan addressing all aspects of the operation along with ethical considerations if applicable.
  agent: fire_personnel_specialist
