# Firefighting Crew Tasks
taskforce_assignment:
  description: >
    Assign the number of firefighters required for the emergency by analyzing inputs such as the fire type, location, and severity.
  expected_output: >
    A count of firefighters needed along with a detailed action plan.
  agent: personnel_specialist

extinguishing_tools_selection:
  description: >
    Select the appropriate tools for extinguishing the fire based on the fire type and other variables.
  expected_output: >
    A list of firefighting tools with an explanation of their selection.
  agent: fire_type_specialist

building_structure_assessment:
  description: >
    Evaluate the structural integrity of the building to determine rescue and fire suppression strategies.
  expected_output: >
    A rescue strategy, fire suppression strategy, and a detailed explanation of the analysis.
  agent: building_structure_specialist

victim_rescue_planning:
  description: >
    Prioritize the rescue of victims based on their condition and severity of injuries.
  expected_output: >
    An ordered list of victims for rescue and an explanation of the prioritization.
  agent: rescue_specialist

tool_selection:
  description: >
    Select additional firefighting tools required for rescue and suppression based on the strategies.
  expected_output: >
    A list of firefighting tools which were selected and an explanation why these tools are chosen.
  agent: tool_specialist

fire_truck_selection:
  description: >
    Assign fire trucks based on proximity and suitability for the task.
  expected_output: >
    A list of fire trucks selected with a rationale for the decision.
  agent: fire_truck_chief

route_planning:
  description: >
    Determine the most efficient routes for fire trucks to reach the emergency site.
  expected_output: >
    Optimized routes and an explanation of the routing plan.
  agent: fire_truck_chief

final_plan_compilation:
  description: >
    Compile all outputs into a comprehensive firefighting response plan.
  expected_output: >
    A complete firefighting response plan addressing all aspects of the operation.
  agent: personnel_specialist

# Medical Crew Tasks
medical_taskforce_assignment:
  description: >
    Determine the number of doctors required for the medical emergency.
  expected_output: >
    A count of required doctors and an action plan for their deployment.
  agent: personnel_specialist

medical_supplies_preparation:
  description: >
    Compile necessary medical supplies based on the emergency.
  expected_output: >
    A list of medical supplies with justifications for their selection.
  agent: equipment_specialist

hospital_capacity_check:
  description: >
    Evaluate hospital capacities to accommodate injured individuals.
  expected_output: >
    A list of hospital capacities and a detailed explanation of the evaluation process.
  agent: hospital_coordinator

hospital_voting:
  description: >
    Coordinate a voting mechanism to prioritize hospital choices based on capacity and severity of injuries.
  expected_output: >
    A ranked list of hospitals with a detailed explanation of the voting process.
  agent: hospital_coordinator

injury_voting:
  description: >
    Map victims to hospitals based on severity of injuries and hospital availability using a voting process.
  expected_output: >
    A mapping of victims to hospitals and a detailed explanation of the prioritization strategy.
  agent: triage_specialist

ambulance_selection:
  description: >
    Assign ambulances based on proximity and suitability for transporting injured individuals.
  expected_output: >
    A list of selected ambulances and an explanation of their allocation.
  agent: ambulance_coordinator

ambulance_route_planning:
  description: >
    Plan the most efficient routes for ambulances to transport victims to hospitals.
  expected_output: >
    Optimized ambulance routes and a detailed routing plan.
  agent: ambulance_coordinator

medical_final_plan_compilation:
  description: >
    Compile all outputs into a comprehensive medical response plan.
  expected_output: >
    A complete medical response plan covering all aspects of the operation.
  agent: personnel_specialist

# Police Crew Tasks
police_taskforce_assignment:
  description: >
    Assign police officers required for managing the emergency.
  expected_output: >
    A count of required officers and an action plan for their deployment.
  agent: receiver_and_personnel_specialist

perimeter_control_planning:
  description: >
    Plan safety perimeters to secure the area around the emergency site.
  expected_output: >
    Proposed perimeter locations with an explanation of the strategy.
  agent: traffic_specialist

patrol_vehicle_assignment:
  description: >
    Assign patrol vehicles to monitor perimeters and support evacuation.
  expected_output: >
    A list of assigned vehicles and an explanation of their allocation.
  agent: dispatch_specialist

patrol_route_planning:
  description: >
    Plan efficient patrol routes to ensure safety perimeters are monitored effectively.
  expected_output: >
    Optimized patrol routes and a routing strategy explanation.
  agent: dispatch_specialist

police_final_plan_compilation:
  description: >
    Compile all outputs into a comprehensive police response plan.
  expected_output: >
    A complete police response plan addressing all aspects of the operation.
  agent: receiver_and_personnel_specialist

# Emergency Crew Tasks
emergency_alert_distribution:
  description: >
    Distribute emergency alerts and assign tasks to relevant crews.
  expected_output: >
    A list of distributed tasks and an explanation of the distribution logic.
  agent: distributor

situation_report_compilation:
  description: >
    Consolidate subplans from all crews into a comprehensive situation report.
  expected_output: >
    A detailed situation report covering all aspects of the emergency.
  agent: distributor

ethical_consultation:
  description: >
    Evaluate the consolidated plans for ethical concerns and provide recommendations.
  expected_output: >
    A finalized situation report addressing ethical concerns.
  agent: philosopher
