# Medical Crew Tasks
medical_taskforce_assignment:
  description: >
    Determine the number of doctors required for the medical emergency.
  expected_output: >
    A count of required doctors and an action plan for their deployment.
  agent: medical_personnel_specialist

medical_supplies_preparation:
  description: >
    Compile necessary medical supplies based on the emergency.
  expected_output: >
    A list of medical supplies with justifications for their selection.
  agent: equipment_specialist

hospital_capacity_check:
  description: >
    Evaluate hospital capacities to accommodate injured individuals.
  expected_output: >
    A list of hospital capacities and a detailed explanation of the evaluation process.
  agent: hospital_coordinator
  human_input: True

hospital_voting:
  description: >
    Coordinate a voting mechanism to prioritize hospital choices based on capacity and severity of injuries.
  expected_output: >
    A ranked list of hospitals with a detailed explanation of the voting process.
  agent: hospital_coordinator

injury_voting:
  description: >
    Map victims to hospitals based on severity of injuries and hospital availability using a voting process.
  expected_output: >
    A mapping of victims to hospitals and a detailed explanation of the prioritization strategy.
  agent: triage_specialist

ambulance_selection:
  description: >
    Assign ambulances based on proximity and suitability for transporting injured individuals.
  expected_output: >
    A list of selected ambulances and an explanation of their allocation.
  agent: ambulance_coordinator

ambulance_route_planning:
  description: >
    Plan the most efficient routes for ambulances to transport victims to hospitals.
  expected_output: >
    Optimized ambulance routes and a detailed routing plan.
  agent: ambulance_coordinator

medical_final_plan_compilation:
  description: >
    Compile all outputs into a comprehensive medical response plan.
  expected_output: >
    A complete medical response plan covering all aspects of the operation.
  agent: medical_personnel_specialist
