situation_report_compilation:
  description: >
    Consolidate subplans from all crews into a comprehensive situation report. If the other crews have raised ethical issues, combine them in the ethical_issues 
    field, ethical issues are the cases in which the resources are not enough to save all the people and a decision has to be made whether to save one person or 
    the other.
  expected_output: >
    A detailed situation report/plan covering all aspects of the emergency and how to solve it, including ethical dilemmas if there are any.
  agent: distributor